trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: eksInfraRepo
      type: github
      name: akash66sheoran/end-to-end-cicd-pipeline
      ref: main
      endpoint: github-service-connection


stages:
  - stage: terraform
    displayName: Provision EKS cluster
    jobs:
      - job: Terraform
        steps:
          - checkout: eksInfraRepo

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: terraform init
            inputs:
              provider: 'aws'
              command: 'init'
              workingDirectory: '$(Build.SourcesDirectory)/eksInfraRepo'

          - task: TerraformTask@5
            displayName: terraform plan
            inputs:
              provider: 'aws'
              command: 'plan'
              workingDirectory: '$(Build.SourcesDirectory)/eksInfraRepo'
              commandOptions: '--var-file=variables.tfvars'
              environmentServiceNameAWS: 'aws-svc'