trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: eksInfraRepo
      type: github
      name: akash66sheoran/tf-aws-eks
      ref: main
      endpoint: github-service-connection


stages:
  - stage: terraform
    displayName: Provision EKS cluster
    jobs:
      - job: Terraform
        steps:
          - checkout: eksInfraRepo

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - script: |
              terraform init
            displayName: terraform init
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              terraform plan --var-file=variables.tfvars
            displayName: terraform plan
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              terraform apply --var-file=variables.tfvars --auto-approve
            displayName: terraform apply
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - stage: terraformDestroy
    displayName: Destroy EKS cluster
    jobs:
      - job: Terraform
        steps:
          - checkout: eksInfraRepo

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - script: |
              terraform init
            displayName: terraform init
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              terraform destroy --var-file=variables.tfvars --auto-approve
            displayName: terraform destroy
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)