trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: eksInfraRepo
      type: github
      name: akash66sheoran/end-to-end-cicd-pipeline
      ref: main
      endpoint: github-service-connection


stages:
  - stage: terraform
    displayName: Provision EKS cluster
    jobs:
      - job: Terraform
        steps:
          - checkout: eksInfraRepo

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - script: |
            displayName: terraform init
              cd $(Build.SourcesDirectory)/infraRepo
              terraform init
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
            displayName: terraform plan
              cd $(Build.SourcesDirectory)/infraRepo
              terraform plan --var-file=variables.tfvars
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)